import 'dart:io';
import 'dart:ui' as ui;
import 'dart:typed_data'; // Add this import
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import 'trend_service.dart';

class TrendExportService {
  static Future<void> shareToWhatsApp(
    GlobalKey chartKey,
    List<TrendDataPoint> trendData,
  ) async {
    try {
      // Generate image from chart
      final imageFile = await _captureChart(chartKey, trendData);

      if (imageFile != null) {
        // Share to WhatsApp
        await Share.shareXFiles([
          XFile(imageFile.path),
        ], text: 'My Vital Signs Trends - Generated by mmWave Vital Monitor');
      }
    } catch (e) {
      debugPrint('Error sharing to WhatsApp: $e');
      rethrow;
    }
  }

  static Future<File?> _captureChart(
    GlobalKey chartKey,
    List<TrendDataPoint> trendData,
  ) async {
    try {
      // Find the RenderRepaintBoundary
      RenderRepaintBoundary? boundary =
          chartKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;

      if (boundary == null) {
        debugPrint('Could not find chart boundary');
        return null;
      }

      // Capture the image
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(
        format: ui.ImageByteFormat.png,
      );

      if (byteData == null) {
        debugPrint('Failed to convert image to bytes');
        return null;
      }

      // Save to temporary directory
      final directory = await getTemporaryDirectory();
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
      final filePath = '${directory.path}/vital_trends_$timestamp.png';
      final file = File(filePath);

      await file.writeAsBytes(byteData.buffer.asUint8List());

      debugPrint('Chart image saved to: $filePath');
      return file;
    } catch (e) {
      debugPrint('Error capturing chart: $e');
      return null;
    }
  }

  static String _generateTextSummary(List<TrendDataPoint> trendData) {
    if (trendData.isEmpty) return 'No data available';

    final hrValues = trendData.map((d) => d.heartRate).toList();
    final brValues = trendData.map((d) => d.breathRate).toList();

    final avgHR = hrValues.reduce((a, b) => a + b) / hrValues.length;
    final avgBR = brValues.reduce((a, b) => a + b) / brValues.length;
    final minHR = hrValues.reduce((a, b) => a < b ? a : b);
    final maxHR = hrValues.reduce((a, b) => a > b ? a : b);
    final minBR = brValues.reduce((a, b) => a < b ? a : b);
    final maxBR = brValues.reduce((a, b) => a > b ? a : b);

    final duration = trendData.last.timestamp.difference(
      trendData.first.timestamp,
    );
    final minutes = duration.inMinutes;

    return '''
📊 Vital Signs Trends Summary

⏱️ Duration: $minutes minutes
📅 ${DateFormat('MMM dd, yyyy HH:mm').format(trendData.last.timestamp)}

❤️ Heart Rate:
  • Average: ${avgHR.toStringAsFixed(1)} BPM
  • Min: ${minHR.toStringAsFixed(1)} BPM
  • Max: ${maxHR.toStringAsFixed(1)} BPM

🫁 Breathing Rate:
  • Average: ${avgBR.toStringAsFixed(1)} breaths/min
  • Min: ${minBR.toStringAsFixed(1)} breaths/min
  • Max: ${maxBR.toStringAsFixed(1)} breaths/min

Generated by mmWave Vital Monitor
    ''';
  }
}
